name: Bundlemon
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node and install dependencies
        uses: ./.github/actions/setup-node/
      - name: Build
        run: npm run build
        shell: bash
      - name: Run Bundlemon
        uses: lironer/bundlemon-action@v1
