# name: Build and publish image to Docker Hub
# on: [workflow_dispatch]
# jobs:
#   build_image:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4
#       - name: Login to DockerHub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_HUB_USERNAME }}
#           password: ${{ secrets.DOCKER_HUB_TOKEN }}
#       - name:
#         uses: docker/build-push-action@v4
#         with:
#           context: . #where to find the Dockerfile that will be used to build the image to be pushed
#           push: true
#           tags: ${{ secrets.DOCKER_HUB_USERNAME }}/test:latest
#       - name: Scan for vulnerabilities
#         uses: crazy-max/ghaction-container-scan@v3
#         with:
#           image: ${{ secrets.DOCKER_HUB_USERNAME }}/test:latest

name: Deploy static Next.js application files to GitHub Pages

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    environment: # is needed for the actions?
      name: github-pages # why? couldn't find it anywhere in the actions repos
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Node.js and dependencies
        uses: ./.github/actions/setup-node/
      - name: Build static files
        run: npm run build
      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
      - name: Deploy to GitHub Pages # This step is skipped if the workflow was triggered by a pull request.
        id: deployment
        uses: actions/deploy-pages@v4
