name: CI Pipeline
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Node setup and install dependencies
        uses: ./.github/actions/setup-node/
      - name: Run Linter
        run: npm run lint
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Node setup and install dependencies
        uses: ./.github/actions/setup-node/
      - name: Run Jest tests
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Node setup and install dependencies
        uses: ./.github/actions/setup-node/
      - name: Build application
        run: npm run build
