name: Dependency Check for security vulnerabilities
on: push

jobs:
  dependy-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Node setup and install dependencies
        uses: ./.github/actions/setup-node/
      - name: Check dependencies
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'test'
          path: '.'
          format: 'HTML'
      - name: Upload Test results
        uses: actions/upload-artifact@v4
        with:
          name: Depcheck report
          path: ${{github.workspace}}/reports
