name: Dependency Check for security vulnerabilities
on: push

jobs:
  dependy-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Node setup and install dependencies
        uses: ./.github/actions/setup-node/
      - name: Run Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          path: '.'
          project: 'cicd'
          format: 'JSON'
          out: './reports'
      - name: Analyze Report for Critical Vulnerabilities
        run: |
          CRITICAL_COUNT=$(jq '[.dependencies[] | .vulnerabilities[] | select(.cvssScore >= 9.0)] | length' ./reports/dependency-check-report.json)
          echo "Found $CRITICAL_COUNT critical vulnerabilities"
          if [ "$CRITICAL_COUNT" -gt 0 ]; then
            echo "Critical vulnerabilities found. Failing the pipeline."
            exit 1
          fi
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: ${{github.workspace}}/reports
